# Generated by Django 5.2.4 on 2025-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم بالعربية'),
        ),
        migrations.AddField(
            model_name='eventtype',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom en français'),
        ),
    ]
