# Generated by Django 5.2.4 on 2025-07-21 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_reservation'),
        ('wilayas', '0008_remove_commune_postal_code_commune_post_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayas.commune'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.eventtype'),
            preserve_default=False,
        ),
    ]
