# Generated by Django 5.2.4 on 2025-07-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='event_types',
            field=models.ManyToManyField(related_name='service_categories', to='events.eventtype', verbose_name='Event Types'),
        ),
    ]
