# Generated by Django 5.2.4 on 2025-07-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('services', '0002_servicecategory_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='event_types',
            field=models.ManyToManyField(related_name='services', to='events.eventtype', verbose_name='Event Types'),
        ),
    ]
