# Generated by Django 5.2.4 on 2025-07-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicecategory_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['category', 'name_ar', 'name_fr']},
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
