# Generated by Django 5.2.4 on 2025-07-06 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0001_initial'),
        ('wilaya', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='ar_name',
        ),
        migrations.RemoveField(
            model_name='commune',
            name='post_code',
        ),
        migrations.AddField(
            model_name='commune',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='commune',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wilaya.wilaya'),
        ),
    ]
