# Generated by Django 5.2.4 on 2025-07-06 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('commune', '0001_initial'),
        ('eventtype', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='client.client')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='commune.commune')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='eventtype.eventtype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
