# Generated by Django 5.2.4 on 2025-07-07 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wilayas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commune',
            old_name='name_ar',
            new_name='ar_name',
        ),
    ]
