# Generated by Django 5.2.4 on 2025-07-08 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayas', '0002_rename_name_ar_commune_ar_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='ar_name',
        ),
        migrations.RemoveField(
            model_name='wilaya',
            name='ar_name',
        ),
        migrations.AddField(
            model_name='commune',
            name='name_ar',
            field=models.CharField(default='غير محدد', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commune',
            name='name_fr',
            field=models.CharField(default='no detail', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commune',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='name_ar',
            field=models.CharField(default='no detail', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wilaya',
            name='name_fr',
            field=models.CharField(default='no detail', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commune',
            name='wilaya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='wilayas.wilaya'),
        ),
    ]
