# Generated by Django 5.2.4 on 2025-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayas', '0003_remove_commune_ar_name_remove_wilaya_ar_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
