# Generated by Django 5.2.4 on 2025-07-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayas', '0004_alter_commune_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
