# Generated by Django 5.2.4 on 2025-07-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wilayas', '0007_remove_commune_name_ar_remove_wilaya_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commune',
            name='postal_code',
        ),
        migrations.AddField(
            model_name='commune',
            name='post_code',
            field=models.CharField(default='arab', max_length=10),
            preserve_default=False,
        ),
    ]
