# Generated by Django 5.2.4 on 2025-07-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Event Location Type',
                'verbose_name_plural': 'Event Location Types',
                'ordering': ['name'],
            },
        ),
    ]
