# Generated by Django 5.2.4 on 2025-07-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_eventlocationtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventLocation',
        ),
    ]
