# Generated by Django 5.2.4 on 2025-07-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_delete_eventlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
