# Generated by Django 5.2.4 on 2025-07-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('prestataires', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='event_types',
            field=models.ManyToManyField(related_name='prestataires', to='events.eventtype', verbose_name='Event Types'),
        ),
    ]
