# Generated by Django 5.2.4 on 2025-07-08 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventtype_name_ar_eventtype_name_fr'),
        ('prestataires', '0003_prestataire_event_types'),
        ('wilayas', '0002_rename_name_ar_commune_ar_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestataire',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.AddField(
            model_name='prestataire',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayas.commune'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='name_fr',
            field=models.CharField(default='Nom par défaut', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestataire',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wilayas.wilaya'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='event_types',
            field=models.ManyToManyField(blank=True, related_name='prestataires', to='events.eventtype', verbose_name='Event Types'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestataire_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
