# Generated by Django 5.2.4 on 2025-07-08 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0004_rename_name_prestataire_name_ar_prestataire_commune_and_more'),
        ('wilayas', '0002_rename_name_ar_commune_ar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestataire',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestataires', to='wilayas.commune'),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestataires', to='wilayas.wilaya'),
        ),
    ]
