# Generated by Django 5.2.4 on 2025-07-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0005_alter_prestataire_commune_alter_prestataire_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestataire',
            name='service_type',
            field=models.CharField(choices=[('service1', 'Service 1'), ('service2', 'Service 2'), ('service3', 'Service 3')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
