# Generated by Django 5.2.4 on 2025-07-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prestataires', '0009_alter_prestataire_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestataire',
            name='name_ar',
        ),
    ]
